version: '2'
services:
  jenkinstest-app:
    image: jenkinstest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jenkinstest-mysql:3306/jenkinstest?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jenkinstest-mysql:
    extends:
      file: mysql.yml
      service: jenkinstest-mysql
